"""Add email column to player's table

Revision ID: 2c5b722e94ef
Revises: f44bf3dc0651
Create Date: 2025-12-05 16:36:19.299987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5b722e94ef'
down_revision: Union[str, Sequence[str], None] = 'f44bf3dc0651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('games', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'genres', ['genre_id'], ['id'])
    op.drop_column('games', 'players_id')
    op.drop_column('games', 'name')
    op.drop_column('games', 'created_at')
    op.create_unique_constraint(None, 'genres', ['name'])
    op.drop_constraint(None, 'genres', type_='foreignkey')
    op.drop_column('genres', 'games_id')
    op.alter_column('player_games', 'review',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('players', sa.Column('email', sa.String(length=150), nullable=False))
    op.create_unique_constraint(None, 'players', ['email'])
    op.create_unique_constraint(None, 'players', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'email')
    op.alter_column('player_games', 'review',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('genres', sa.Column('games_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'genres', 'games', ['games_id'], ['id'])
    op.drop_constraint(None, 'genres', type_='unique')
    op.add_column('games', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('games', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('games', sa.Column('players_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'players', ['players_id'], ['id'])
    op.drop_column('games', 'genre_id')
    op.drop_column('games', 'description')
    op.drop_column('games', 'title')
    # ### end Alembic commands ###
